Vagrant.configure("2") do |config|
    config.vm.box = "generic/ubuntu2204"

    # example of multimachine config
    # config.vm.define "web" do |web|
    #     web.vm.box = "apache"
    #   end
    
    #   config.vm.define "db" do |db|
    #     db.vm.box = "mysql"
    #   end

    config.vm.provider "hyperv"
  end